# ***Importing our tools***

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# ***Data Ingestion***

In [2]:
from google.colab import files

uploaded = files.upload()

Saving movies.csv to movies.csv

# *Loading the data cell*

In [3]:
df=pd.read_csv('/content/movies.csv')

# ***Exploriatry Data Analysis***

In [4]:
df.shape

(250, 22)

In [ ]:
df.columns

Index(['rank', 'movie_id', 'title', 'year', 'link', 'imbd_votes',
       'imbd_rating', 'certificate', 'duration', 'genre', 'cast_id',
       'cast_name', 'director_id', 'director_name', 'writer_id', 'writer_name',
       'storyline', 'user_id', 'user_name', 'review_id', 'review_title',
       'review_content'],
      dtype='object')

In [5]:
df.head()

,rank,movie_id,title,year,link,imbd_votes,imbd_rating,certificate,duration,genre,...,director_id,director_name,writer_id,writer_name,storyline,user_id,user_name,review_id,review_title,review_content
0,1,tt0111161,The Shawshank Redemption,1994,https://www.imdb.com/title/tt0111161,"2,711,075",9.3,R,2h 22m,Drama,...,nm0001104,Frank Darabont,"nm0000175,nm0001104","Stephen King,Frank Darabont","Over the course of several years, two convicts...","ur16161013,ur15311310,ur0265899,ur16117882,ur1...","hitchcockthelegend,Sleepin_Dragon,EyeDunno,ale...","rw2284594,rw6606154,rw1221355,rw1822343,rw1288...","Some birds aren't meant to be caged.,An incred...",The Shawshank Redemption is written and direct...
1,2,tt0068646,The Godfather,1972,https://www.imdb.com/title/tt0068646,"1,882,829",9.2,R,2h 55m,"Crime,Drama",...,nm0000338,Francis Ford Coppola,"nm0701374,nm0000338","Mario Puzo,Francis Ford Coppola",The aging patriarch of an organized crime dyna...,"ur24740649,ur86182727,ur15794099,ur15311310,ur...","CalRhys,andrewburgereviews,gogoschka-1,Sleepin...","rw3038370,rw4756923,rw4059579,rw6568526,rw1897...","The Pinnacle Of Flawless Films!,An offer so go...",'The Godfather' is the pinnacle of flawless fi...
2,3,tt0468569,The Dark Knight,2008,https://www.imdb.com/title/tt0468569,"2,684,051",9.0,PG-13,2h 32m,"Action,Crime,Drama",...,nm0634240,Christopher Nolan,"tt0468569,nm0634300,nm0634240,nm0275286,tt0468569","Writers,Jonathan Nolan,Christopher Nolan,David...",When the menace known as the Joker wreaks havo...,"ur87850731,ur1293485,ur129557514,ur12449122,ur...","MrHeraclius,Smells_Like_Cheese,dseferaj,little...","rw5478826,rw1914442,rw6606026,rw1917099,rw5170...","The Dark Knight,The Batman of our dreams! So m...","Confidently directed, dark, brooding, and pack..."
3,4,tt0071562,The Godfather Part II,1974,https://www.imdb.com/title/tt0071562,"1,285,350",9.0,R,3h 22m,"Crime,Drama",...,nm0000338,Francis Ford Coppola,"nm0000338,nm0701374","Francis Ford Coppola,Mario Puzo",The early life and career of Vito Corleone in ...,"ur0176092,ur0688559,ur92260614,ur0200644,ur117...","Nazi_Fighter_David,tfrizzell,umunir-36959,DanB...","rw0135607,rw0135487,rw5049900,rw0135526,rw0135...",Breathtaking in its scope and tragic grandeur....,"Coppola's masterpiece is rivaled only by ""The ..."
4,5,tt0050083,12 Angry Men,1957,https://www.imdb.com/title/tt0050083,"800,954",9.0,Approved,1h 36m,"Crime,Drama",...,nm0001486,Sidney Lumet,nm0741627,Reginald Rose,The jury in a New York City murder trial is fr...,"ur1318549,ur0643062,ur0688559,ur20552756,ur945...","uds3,tedg,tfrizzell,TheLittleSongbird,henrique...","rw0060044,rw0060025,rw0060034,rw2262425,rw5448...","The over-used term ""classic movie"" really come...",This once-in-a-generation masterpiece simply h...

In [6]:
df=df[['rank','title','year','imbd_votes','imbd_rating','certificate','duration','genre','director_name']]

In [7]:
df.head()

,rank,title,year,imbd_votes,imbd_rating,certificate,duration,genre,director_name
0,1,The Shawshank Redemption,1994,"2,711,075",9.3,R,2h 22m,Drama,Frank Darabont
1,2,The Godfather,1972,"1,882,829",9.2,R,2h 55m,"Crime,Drama",Francis Ford Coppola
2,3,The Dark Knight,2008,"2,684,051",9.0,PG-13,2h 32m,"Action,Crime,Drama",Christopher Nolan
3,4,The Godfather Part II,1974,"1,285,350",9.0,R,3h 22m,"Crime,Drama",Francis Ford Coppola
4,5,12 Angry Men,1957,"800,954",9.0,Approved,1h 36m,"Crime,Drama",Sidney Lumet

## *fix column name*

In [8]:
df=df.rename(columns={'imbd_votes':'imdb_votes','imbd_ranking':'imdb_ranking'})

In [9]:
df.head()

,rank,title,year,imdb_votes,imbd_rating,certificate,duration,genre,director_name
0,1,The Shawshank Redemption,1994,"2,711,075",9.3,R,2h 22m,Drama,Frank Darabont
1,2,The Godfather,1972,"1,882,829",9.2,R,2h 55m,"Crime,Drama",Francis Ford Coppola
2,3,The Dark Knight,2008,"2,684,051",9.0,PG-13,2h 32m,"Action,Crime,Drama",Christopher Nolan
3,4,The Godfather Part II,1974,"1,285,350",9.0,R,3h 22m,"Crime,Drama",Francis Ford Coppola
4,5,12 Angry Men,1957,"800,954",9.0,Approved,1h 36m,"Crime,Drama",Sidney Lumet

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   rank           250 non-null    int64
 1   title          250 non-null    object
 2   year           250 non-null    int64
 3   imdb_votes     250 non-null    object
 4   imbd_rating    250 non-null    float64
 5   certificate    249 non-null    object
 6   duration       250 non-null    object
 7   genre          250 non-null    object
 8   director_name  250 non-null    object
dtypes: float64(1), int64(2), object(6)
memory usage: 17.7+ KB

Data investigation

In [11]:
df.isnull().sum()

rank             0
title            0
year             0
imdb_votes       0
imbd_rating      0
certificate      1
duration         0
genre            0
director_name    0
dtype: int64

In [12]:
df['certificate'].isnull()

0      False
1      False
2      False
3      False
4      False
       ...
245    False
246    False
247    False
248    False
249    False
Name: certificate, Length: 250, dtype: bool

In [13]:
df[df['certificate'].isnull()]

,rank,title,year,imdb_votes,imbd_rating,certificate,duration,genre,director_name
76,77,The Boat,1981,"253,534",8.4,NaN,2h 29m,"Drama,War",Wolfgang Petersen

In [14]:
df['certificate'].fillna('not rated')

0             R
1             R
2         PG-13
3             R
4      Approved
         ...
245           G
246       PG-13
247           G
248          PG
249       PG-13
Name: certificate, Length: 250, dtype: object

In [15]:
df['certificate']=df['certificate'].fillna('not rated')

In [ ]:
df.isnull().sum()

rank             0
title            0
year             0
imdb_votes       0
imbd_rating      0
certificate      0
duration         0
genre            0
director_name    0
dtype: int64

In [16]:
df.iloc[76]

rank                            77
title                     The Boat
year                          1981
imdb_votes                 253,534
imbd_rating                    8.4
certificate              not rated
duration                    2h 29m
genre                    Drama,War
director_name    Wolfgang Petersen
Name: 76, dtype: object

## *check douplicate rows*

In [17]:
df.duplicated().sum()

np.int64(0)

## ***clean imdb votes***

In [18]:
df['imdb_votes']

0      2,711,075
1      1,882,829
2      2,684,051
3      1,285,350
4        800,954
         ...
245       31,167
246      466,011
247      429,219
248      234,688
249      271,823
Name: imdb_votes, Length: 250, dtype: object

In [19]:
'2,711,075'.replace(',','')

'2711075'

In [20]:
df['imdb_votes'].str.replace(',','').astype(int)

0      2711075
1      1882829
2      2684051
3      1285350
4       800954
        ...
245      31167
246     466011
247     429219
248     234688
249     271823
Name: imdb_votes, Length: 250, dtype: int64

In [21]:
df['imdb_votes']=df['imdb_votes'].str.replace(',','').astype(int)

In [22]:
df['imdb_votes']

0      2711075
1      1882829
2      2684051
3      1285350
4       800954
        ...
245      31167
246     466011
247     429219
248     234688
249     271823
Name: imdb_votes, Length: 250, dtype: int64

# **Day14_Data_visualization_part_2.ipynb**

In [23]:
df

,rank,title,year,imdb_votes,imbd_rating,certificate,duration,genre,director_name
0,1,The Shawshank Redemption,1994,2711075,9.3,R,2h 22m,Drama,Frank Darabont
1,2,The Godfather,1972,1882829,9.2,R,2h 55m,"Crime,Drama",Francis Ford Coppola
2,3,The Dark Knight,2008,2684051,9.0,PG-13,2h 32m,"Action,Crime,Drama",Christopher Nolan
3,4,The Godfather Part II,1974,1285350,9.0,R,3h 22m,"Crime,Drama",Francis Ford Coppola
4,5,12 Angry Men,1957,800954,9.0,Approved,1h 36m,"Crime,Drama",Sidney Lumet
...,...,...,...,...,...,...,...,...,...
245,246,Dersu Uzala,1975,31167,8.2,G,2h 22m,"Adventure,Biography,Drama",Akira Kurosawa
246,247,The Help,2011,466011,8.1,PG-13,2h 26m,Drama,Tate Taylor
247,248,Aladdin,1992,429219,8.0,G,1h 30m,"Animation,Adventure,Comedy","Ron Clements,John Musker"
248,249,Gandhi,1982,234688,8.0,PG,3h 11m,"Biography,Drama,History",Richard Attenborough
249,250,Dances with Wolves,1990,271823,8.0,PG-13,3h 1m,"Adventure,Drama,Western",Kevin Costner

# **Cleaning movie duration column**

In [24]:
df.head()

,rank,title,year,imdb_votes,imbd_rating,certificate,duration,genre,director_name
0,1,The Shawshank Redemption,1994,2711075,9.3,R,2h 22m,Drama,Frank Darabont
1,2,The Godfather,1972,1882829,9.2,R,2h 55m,"Crime,Drama",Francis Ford Coppola
2,3,The Dark Knight,2008,2684051,9.0,PG-13,2h 32m,"Action,Crime,Drama",Christopher Nolan
3,4,The Godfather Part II,1974,1285350,9.0,R,3h 22m,"Crime,Drama",Francis Ford Coppola
4,5,12 Angry Men,1957,800954,9.0,Approved,1h 36m,"Crime,Drama",Sidney Lumet

In [25]:
df['duration']

0      2h 22m
1      2h 55m
2      2h 32m
3      3h 22m
4      1h 36m
        ...
245    2h 22m
246    2h 26m
247    1h 30m
248    3h 11m
249     3h 1m
Name: duration, Length: 250, dtype: object

In [26]:
'2h 22m'

'2h 22m'

In [31]:
import re

In [33]:
re.findall(r'(\d+)h','2h 22m')

['2']

In [35]:
re.findall(r'(\d+)h','2h 22m')[0]

'2'

In [36]:
int(re.findall(r'(\d+)h','2h 22m')[0])

2

In [40]:
int(re.findall(r'(\d+)h','2h 22m')[0])*60

120

In [42]:
re.findall(r'(\d+)m','2h 22m')

['22']

In [43]:
re.findall(r'(\d+)m','2h 22m')[0]

'22'

In [44]:
int(re.findall(r'(\d+)m','2h 22m')[0])

22

In [45]:
int(re.findall(r'(\d+)h','2h 22m')[0])*60 + int(re.findall(r'(\d+)m','2h 22m')[0])

142

In [51]:
df['duration']

0      2h 22m
1      2h 55m
2      2h 32m
3      3h 22m
4      1h 36m
        ...
245    2h 22m
246    2h 26m
247    1h 30m
248    3h 11m
249     3h 1m
Name: duration, Length: 250, dtype: object

In [56]:
for i in df['duration']:
  print(i)
  print(int(re.findall(r'(\d+)h',i)[0])*60 + int(re.findall(r'(\d+)m',i)[0]))

2h 22m
142
2h 55m
175
2h 32m
152
3h 22m
202
1h 36m
96
3h 15m
195
3h 21m
201
2h 34m
154
2h 58m
178
2h 58m
178
2h 22m
142
2h 19m
139
2h 59m
179
2h 28m
148
2h 4m
124
2h 16m
136
2h 25m
145
2h 13m
133
2h 7m
127
3h 27m
207
2h 10m
130
1h 58m
118
2h 49m
169
2h 10m
130
2h 49m
169
1h 56m
116
3h 9m
189
2h 1m
121
2h 17m
137
1h 56m
116
2h 5m
125
2h 30m
150
1h 49m
109
2h 12m
132
1h 50m
110
1h 28m
88
2h 35m
155
1h 59m
119
2h 31m
151
1h 46m
106
2h 10m
130
1h 46m
106
1h 42m
102
1h 29m
89
2h 13m
133
1h 52m
112
1h 27m
87
2h 45m
165
2h 35m
155
1h 52m
112
1h 57m
117
1h 27m
87
2h 27m
147
1h 53m
113
2h 45m
165
1h 55m
115
1h 38m
98
2h 17m
137
1h 50m
110
1h 28m
88
2h 26m
146
2h 5m
125
2h 29m
149
1h 56m
116
2h 17m
137
1h 57m
117
2h 2m
122
1h 35m
95
2h 44m
164
2h

IndexError: list index out of range

In [ ]:
for i in df['duration']:
  print(i)
  if('h' and 'm' in df['duration']= True ):
        print(int(re.findall(r'(\d+)h','2h 22m')[0])*60 + int(re.findall(r'(\d+)m','2h 22m')[0]))

  else('h'in df['duration']= True):
    print()

In [60]:
'h' and 'm' in '2h 22m'

True

In [58]:
'h' in '2h 22m'

True

In [59]:
'm' in '2h 22m'

True