Importing nesesary library

In [1]:
import pandas as pd

creating dataframe

In [2]:
data={'name':['Alice','Bob','Carlie'],'age':[25,30,35],'city':['delhi','mumbai','chennai']}

In [3]:
data

{'name': ['Alice', 'Bob', 'Carlie'],
 'age': [25, 30, 35],
 'city': ['delhi', 'mumbai', 'chennai']}

In [4]:
df=pd.DataFrame(data)

In [5]:
df

     name  age     city
0   Alice   25    delhi
1     Bob   30   mumbai
2  Carlie   35  chennai

Dataframe Operations

Accesing data

In [6]:
df

     name  age     city
0   Alice   25    delhi
1     Bob   30   mumbai
2  Carlie   35  chennai

In [7]:
df['name']

0     Alice
1       Bob
2    Carlie
Name: name, dtype: object

In [8]:
df['city']

0      delhi
1     mumbai
2    chennai
Name: city, dtype: object

In [10]:
df[['name','age']]

     name  age
0   Alice   25
1     Bob   30
2  Carlie   35

In [11]:
df.iloc[0]

name    Alice
age        25
city    delhi
Name: 0, dtype: object

In [12]:
df.iloc[2]

name     Carlie
age          35
city    chennai
Name: 2, dtype: object

In [13]:
df.iloc[[0,1]]

    name  age    city
0  Alice   25   delhi
1    Bob   30  mumbai

In [14]:
df [['age','city']].iloc[[1,2]]

   age     city
1   30   mumbai
2   35  chennai

In [15]:
df

     name  age     city
0   Alice   25    delhi
1     Bob   30   mumbai
2  Carlie   35  chennai

adding new coloum

In [16]:
df

     name  age     city
0   Alice   25    delhi
1     Bob   30   mumbai
2  Carlie   35  chennai

In [17]:
df['salary']=[10000,20000,30000]

In [18]:
df

     name  age     city  salary
0   Alice   25    delhi   10000
1     Bob   30   mumbai   20000
2  Carlie   35  chennai   30000

Deliting a column

In [19]:
df

     name  age     city  salary
0   Alice   25    delhi   10000
1     Bob   30   mumbai   20000
2  Carlie   35  chennai   30000

In [20]:
del df ['city']

In [21]:
df

     name  age  salary
0   Alice   25   10000
1     Bob   30   20000
2  Carlie   35   30000

filtering Data

In [22]:
df

     name  age  salary
0   Alice   25   10000
1     Bob   30   20000
2  Carlie   35   30000

In [24]:
df['age']>=30

0    False
1     True
2     True
Name: age, dtype: bool

In [25]:
df[df['age']>=30]

     name  age  salary
1     Bob   30   20000
2  Carlie   35   30000

# ***special function***

In [26]:
df.shape

(3, 3)

In [28]:
df.columns

Index(['name', 'age', 'salary'], dtype='object')

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      object
 1   age     3 non-null      int64
 2   salary  3 non-null      int64
dtypes: int64(2), object(1)
memory usage: 204.0+ bytes

In [33]:
df.describe()

        age   salary
count   3.0      3.0
mean   30.0  20000.0
std     5.0  10000.0
min    25.0  10000.0
25%    27.5  15000.0
50%    30.0  20000.0
75%    32.5  25000.0
max    35.0  30000.0

# ***Activity 1***

1) Create the dataframe using pandas

In [44]:
data1={'festival':['diwali','chrishmas','pongal','eid','hailoween'],'month':['oct','dec','jan','varies','oct']
       ,'country':['india','worldwide','india','worldwide','usa'],'hoiday':['yes','yes','yes','yes','no']}

In [45]:
data1

{'festival': ['diwali', 'chrishmas', 'pongal', 'eid', 'hailoween'],
 'month': ['oct', 'dec', 'jan', 'varies', 'oct'],
 'country': ['india', 'worldwide', 'india', 'worldwide', 'usa'],
 'hoiday': ['yes', 'yes', 'yes', 'yes', 'no']}

In [46]:
dt=pd.DataFrame(data1)

In [47]:
dt

    festival   month    country hoiday
0     diwali     oct      india    yes
1  chrishmas     dec  worldwide    yes
2     pongal     jan      india    yes
3        eid  varies  worldwide    yes
4  hailoween     oct        usa     no

2) Display the compleat dataframe

In [48]:
dt

    festival   month    country hoiday
0     diwali     oct      india    yes
1  chrishmas     dec  worldwide    yes
2     pongal     jan      india    yes
3        eid  varies  worldwide    yes
4  hailoween     oct        usa     no

3) display festival column only

In [49]:
dt ['festival']

0       diwali
1    chrishmas
2       pongal
3          eid
4    hailoween
Name: festival, dtype: object

# 4) Display contry column

In [51]:
dt ['country']

0        india
1    worldwide
2        india
3    worldwide
4          usa
Name: country, dtype: object

5) display frist row only

In [52]:
dt.iloc[0]

festival    diwali
month          oct
country      india
hoiday         yes
Name: 0, dtype: object

6) display last 2 rows

In [53]:
dt.iloc[[3,4]]

    festival   month    country hoiday
3        eid  varies  worldwide    yes
4  hailoween     oct        usa     no

# **7) Add a new column named 'season' with autumn,winter,winter,spring,auttumn**

In [54]:
dt['season']=['autumn','winter','winter','spring','autumn']

In [55]:
dt

    festival   month    country hoiday  season
0     diwali     oct      india    yes  autumn
1  chrishmas     dec  worldwide    yes  winter
2     pongal     jan      india    yes  winter
3        eid  varies  worldwide    yes  spring
4  hailoween     oct        usa     no  autumn

# **8) display all the data where it is yes**

In [62]:
 dt[dt['hoiday']=='yes']

    festival   month    country hoiday  season
0     diwali     oct      india    yes  autumn
1  chrishmas     dec  worldwide    yes  winter
2     pongal     jan      india    yes  winter
3        eid  varies  worldwide    yes  spring

9) filter only festival where country

In [66]:
dt[dt['country']=='india']

  festival month country hoiday  season
0   diwali   oct   india    yes  autumn
2   pongal   jan   india    yes  winter

# **10) deleta holiday column**

In [68]:
del dt ['hoiday']

In [69]:
dt

    festival   month    country  season
0     diwali     oct      india  autumn
1  chrishmas     dec  worldwide  winter
2     pongal     jan      india  winter
3        eid  varies  worldwide  spring
4  hailoween     oct        usa  autumn

# **Activity 2**



1.   to use pandas library, we write import **pandas** as pd
2.   A **dataframe** is 2D table in pandas
3.   to save Dataframe as csv file df.**to_csv**('student.csv")
4.   to read csv file pd.**read_csv** (student.csv)
5.   to find number of rows and coloumn df.**shape**
6.   to find statistical inferance df.**describe()**
7.   to delete city column **del** df [city]