# **Installing pandas**

In [5]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

# **Importing pandas**

In [6]:
import pandas as pd

## **creating dictionary**

In [7]:
dic1={'name':['Alice','Bob','Carlie'],'age':[25,30,35],'city':['delhi','mumbai','chennai']}

In [10]:
dic1

{'name': ['Alice', 'Bob', 'Carlie'],
 'age': [25, 30, 35],
 'city': ['delhi', 'mumbai', 'chennai']}

# **creating dataframe from dictionary**

In [12]:
df=pd.DataFrame(dic1)

In [13]:
df

     name  age     city
0   Alice   25    delhi
1     Bob   30   mumbai
2  Carlie   35  chennai

# **saving the dataframe**

In [14]:
df.to_csv('student.csv')

In [16]:
df.to_csv('student_1.csv',index=False)

In [17]:
df

     name  age     city
0   Alice   25    delhi
1     Bob   30   mumbai
2  Carlie   35  chennai

# **opening the csv file**

In [1]:
df

NameError: name 'df' is not defined

In [8]:
df=pd.read_csv('/content/student_1.csv')

In [9]:
df

     name  age     city
0   Alice   25    delhi
1     Bob   30   mumbai
2  Carlie   35  chennai

# ***Acitivity 1 - create a dataframe and save and open as csv***

In [1]:
dict1={'r.no':[1,2,3,4],'name':['arun','bala','raja','ravi'],'std':[3,5,7,12],'mark':[100,95,91,87]}

In [2]:
import pandas as pd

In [3]:
df2=pd.DataFrame(dict1)

In [4]:
df2

   r.no  name  std  mark
0     1  arun    3   100
1     2  bala    5    95
2     3  raja    7    91
3     4  ravi   12    87

In [6]:
df2.to_csv('marks.csv')

In [8]:
df2.to_csv('marks_1.csv',index=False)

In [3]:
df2=pd.read_csv('/content/marks_1.csv')

In [4]:
df2

   r.no  name  std  mark
0     1  arun    3   100
1     2  bala    5    95
2     3  raja    7    91
3     4  ravi   12    87

**I. list all the feature names**
- r.no
- name
- std
- marks

**II. Total number of records** = 4

**III. total number of features** =4

**IV total number of index and list them** =4
- 0
- 1
- 2
- 3